name = "recipe-solasido"
compatibility_date = "2026-02-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "recipe_db"
database_id = "9fcfed36-33af-46f8-899f-d0277441acc0"
