name = "blog-solasido"
main = ".open-next/worker.js"
compatibility_date = "2025-02-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "blog-solasido"

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "36360ddd-8cef-4953-b208-6b352935f7e2"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "solasido-static-assets"
